companies:
- wba:
    alias:
    - $wba
    - wba
    - walgreen boots alliance inc
    - walgreen boots alliance
    - walgreenbootsalliance
- v:
    alias:
    - $v
    - v
    - visa inc class a
    - visa
- crm:
    alias:
    - $crm
    - crm
    - salesforce.com inc
    - salesforce
- cvx:
    alias:
    - $cvx
    - cvx
    - chevron corp
    - chevron
- pg:
    alias:
    - $pg
    - pg
    - procter & gamble
    - procter&gamble
- vz:
    alias:
    - $vz
    - vz
    - verizon communications inc
    - verizon
- wmt:
    alias:
    - $wmt
    - wmt
    - walmart stores inc
    - walmart stores
    - walmart
- unh:
    alias:
    - $unh
    - unh
    - unitedhealth group inc
    - unitedhealth group
    - unitedhealthgroup
- trv:
    alias:
    - $trv
    - trv
    - travelers companies inc
    - travelers companies
    - travelers
    - travelerscompanies
- mcd:
    alias:
    - $mcd
    - mcd
    - mcdonalds corp
    - mcdonalds
- mmm:
    alias:
    - $mmm
    - mmm
    - 3m
    - 3m
- nke:
    alias:
    - $nke
    - nke
    - nike inc class b
    - nike
- mrk:
    alias:
    - $mrk
    - mrk
    - merck & co inc
    - merck & co
    - merck&co
- msft:
    alias:
    - $msft
    - msft
    - microsoft corp
    - microsoft
- jpm:
    alias:
    - $jpm
    - jpm
    - jp morgan chase & co
    - jp morgan chase
    - jpmorgan
    - ' j.p. morgan'
    - ' jp morgan'
    - jpm
- ko:
    alias:
    - $ko
    - ko
    - coca-cola
    - cocacola
- jnj:
    alias:
    - $jnj
    - jnj
    - johnson & johnson
    - johnson&johnson
- gs:
    alias:
    - $gs
    - gs
    - goldman sachs group inc
    - goldman sachs group
    - goldman sachs
    - goldman
- hd:
    alias:
    - $hd
    - hd
    - home depot inc
    - home depot
- hon:
    alias:
    - $hon
    - hon
    - honeywell international inc
    - honeywell international
    - honeywell
- ibm:
    alias:
    - $ibm
    - ibm
    - international business machines co
    - international business machines
    - internationalbusinessmachines
- intc:
    alias:
    - $intc
    - intc
    - intel corporation corp
    - intel corporation
    - intel
- dis:
    alias:
    - $dis
    - dis
    - walt disney
    - disney
    - waltdisney
- cat:
    alias:
    - $cat
    - cat
    - caterpillar inc
    - caterpillar inc
    - caterpillarinc
- csco:
    alias:
    - $csco
    - csco
    - cisco systems inc
    - cisco systems
    - cisco
- axp:
    alias:
    - $axp
    - axp
    - american express
    - american express
    - amex
    - americanexpress
- ba:
    alias:
    - $ba
    - ba
    - boeing
    - boeing
- amgn:
    alias:
    - $amgn
    - amgn
    - amgen inc
    - amgen
- aapl:
    alias:
    - $aapl
    - aapl
    - apple inc
    - apple inc
    - appleinc
- dow:
    alias:
    - $dow
    - dow
    - dow inc.
    - dow
data_root: ./data
twitter_conifg:
  sleep_time: 5
