companies:
- wba:
    alias:
    - $wba
    - wba
    - walgreen boots alliance inc
    - walgreen boots alliance
    - walgreenbootsalliance
- v:
    alias:
    - $v
    - v
    - visa inc class a
    - visa
data_root: ../data
start_date: 2021-07-01
end_date: 2021-10-01
twitter_conifg:
    sleep_time: 5
etf_config:
    external_path: ../data/external/etf
sec_config:
    parser_config:
        directory: ../data/raw/sec
        amount: 5
        items:
        - "1A"
        - "1B"
        - "7A"
        - "8"
        external_fp: ./data/external/sec
    emb_config:
        input_dir: ./data/raw/sec/parsed
        # output_dir: ./data/raw/sec/emb
        top_k: 20
        model_name: all-mpnet-base-v2
news_config:
    sleep_time: 2
    nyt_key: MN3m4QX4XDbGsaBFDBpJG4waHymmqZ3O
    base_url: https://api.nytimes.com/svc/search/v2/articlesearch.json?
    search_keyword: 
        - 3M
        - American+Express
        - Amgen
        - Apple
        - Boeing
        - Caterpillar
        - Chevron
        - Cisco
        - Coca+Cola
        - Dow
        - Goldman+Sachs
        - Home+Depot
        - Honeywell
        - IBM
        - Intel
        - Johnson+Johnson
        - JPMorgan
        - McDonald
        - Merck
        - Microsoft
        - Nike
        - Procter+Gamble
        - Salesforce
        - Travelers
        - UnitedHealth
        - Verizon
        - Visa
        - Walgreens
        - Walmart
        - Disney
